version: "3.5"
services:
    mysql:
        image: mysql
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: robertfaitdestests
            MYSQL_USER: robertuser
            MYSQL_PASSWORD: robertfaitdestests
            MYSQL_DATABASE: robert
        volumes:
            # - ./ForBuild/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            -./data/db:/var/lib/mysql
    robert-front:
        container_name: $ROBERT_HOSTNAME
        depends_on: 
            - mysql
        environment:
            APACHE_LOG_DIR: /etc/apache/logs
        env_file:
            - .env        
        build: 
            context: ./ForBuild
            args: 
                ROBERT_HOSTNAME: $ROBERT_HOSTNAME

            # context:./ForBuild
            # dockerfile: RobertDockerFile
        ports:
            - 8082:80
        volumes:
            - ./logs/apache:/etc/apache/logs
        # links: 
            # - "${ROBERT_HOSTNAME}:robert-front"
# volumes:
    # db_data: