version: "3.7"

services:
  
  mysql:
    image: mysql:5.7
    volumes:
      - robert-mysql-data:/var/lib/mysql
    expose:
      - "3306"
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: robert
    command : ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - robert-network
    
  app:
    image: todrak/robertbase:0.1.5
    depends_on:
      - mysql
     # command: sh -c "yarn install && yarn run dev"
    ports:
      - 80:80
    networks:
      - robert-network
  
    #environment:
     # MYSQL_HOST: mysql
     # MYSQL_USER: root
      # MYSQL_PASSWORD: secret
      # MYSQL_DB: robert
networks:
  robert-network:    
volumes:
  robert-mysql-data: