name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Run hadolint
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: reviewdog/action-hadolint@v1