name: CI
on: [push]
jobs:
  lint:
    name: Run hadolint
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Hadolint
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile